# Generated by Django 4.1.3 on 2022-11-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoist', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
